/* EDIT YOUR STORE HERE. Prices are USD; crypto conversions use a fixed reference rate.
   Put pictures inside assets/ and set image: 'assets/your-picture.png'.
   Keep every id unique. Art styles: terminal, orbit, grid, wave, cube, code. */
window.MARKET = {
  // Categories expanded based on the screenshot reference
  categories: [
    'Hacking & Spam', 
    'Malware Analysis', 
    'Services', 
    'Security & Hosting', 
    'Guides & Tutorials', 
    'Software', 
    'Digital Items', 
    'Automotive Related',
    'Fraud',
    'Drugs & Chemicals',
    'Counterfeit Items',
  ],
  name: 'Tornet Market', 
  tagline: 'Digital goods. Underground spirit.', 
  btcRate: 65000, 
  startingBalance: 1250,
  products: [
    // --- EXISTING PRODUCTS ---
    { 
      id: 'spectre-shell', 
      name: 'Spectre Shell', 
      category: 'Hacking & Spam', 
      price: 120, 
      badge: 'BESTSELLER', 
      art: 'terminal', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Remote administration redefined.', 
      description: 'A lightweight, encrypted remote administration tool for managing your own infrastructure. Features session logging, multi-user support, and a distraction-free CLI interface.', 
      version: '3.1.0', 
      format: 'ZIP / 14 MB', 
      rating: '4.9', 
      reviews: 342, 
      tags: ['Linux', 'Windows', 'CLI'] 
    },
    { 
      id: 'void-proxy', 
      name: 'Void Proxy Network', 
      category: 'Security & Hosting', 
      price: 45, 
      badge: 'STAFF PICK', 
      art: 'orbit', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Disappear into the noise.', 
      description: 'A decentralized proxy network configuration script. Routes your traffic through multiple encrypted nodes to ensure maximum anonymity for your research.', 
      version: '2.0.4', 
      format: 'PY / 8 MB', 
      rating: '4.8', 
      reviews: 156, 
      tags: ['Python', 'Tor', 'I2P'] 
    },
    { 
      id: 'ironclad-vault', 
      name: 'IronClad Vault', 
      category: 'Software', 
      price: 89, 
      badge: 'VERIFIED', 
      art: 'cube', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'Your secrets, locked away.', 
      description: 'An enterprise-grade password manager and secret storage solution. Features zero-knowledge architecture and hardware key support.', 
      version: '4.2.1', 
      format: 'EXE / 32 MB', 
      rating: '5.0', 
      reviews: 89, 
      tags: ['Security', 'Encryption', '2FA'] 
    },
    { 
      id: 'neon-grid-ui', 
      name: 'Neon Grid UI Kit', 
      category: 'Digital Items', 
      price: 35, 
      badge: 'NEW DROP', 
      art: 'grid', 
      accent: '#eab786', 
      image: '', 
      subtitle: 'The interface is only the beginning.', 
      description: 'A cyberpunk-themed UI kit for your next dashboard project. Includes 50+ components, dark mode presets, and responsive layouts.', 
      version: '1.5.0', 
      format: 'FIG + ZIP / 48 MB', 
      rating: '4.7', 
      reviews: 210, 
      tags: ['React', 'Figma', 'CSS'] 
    },
    { 
      id: 'phantom-node', 
      name: 'Phantom Node VPS', 
      category: 'Security & Hosting', 
      price: 15, 
      badge: 'MONTHLY', 
      art: 'wave', 
      accent: '#d59dc5', 
      image: '', 
      subtitle: 'Offshore hosting for the bold.', 
      description: 'High-performance VPS hosting located in privacy-friendly jurisdictions. DDoS protection included. Perfect for hosting your own services.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '4.6', 
      reviews: 540, 
      tags: ['Hosting', 'Linux', 'Privacy'] 
    },
    { 
      id: 'zerotrace-browser', 
      name: 'ZeroTrace Browser Config', 
      category: 'Software', 
      price: 25, 
      badge: '', 
      art: 'code', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Browse without leaving a footprint.', 
      description: 'A hardened browser configuration profile. Blocks trackers, fingerprints, and ads out of the box. Based on Firefox ESR.', 
      version: '115.0', 
      format: 'JSON / 2 MB', 
      rating: '4.8', 
      reviews: 128, 
      tags: ['Firefox', 'Privacy', 'Config'] 
    },
    { 
      id: 'cryptoguard-wallet', 
      name: 'CryptoGuard Wallet', 
      category: 'Software', 
      price: 60, 
      badge: 'POPULAR', 
      art: 'terminal', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Secure your assets.', 
      description: 'A multi-signature cryptocurrency wallet interface. Supports cold storage integration and hardware wallet bridging.', 
      version: '2.1.0', 
      format: 'ZIP / 18 MB', 
      rating: '4.9', 
      reviews: 95, 
      tags: ['Crypto', 'Security', 'Wallet'] 
    },
    { 
      id: 'shadow-ban-check', 
      name: 'Shadow Ban Checker', 
      category: 'Digital Items', 
      price: 15, 
      badge: '', 
      art: 'orbit', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'Know your status.', 
      description: 'A tool to check if your social media accounts are shadow-banned or restricted. Supports multiple platforms.', 
      version: '1.0.2', 
      format: 'PY / 4 MB', 
      rating: '4.5', 
      reviews: 67, 
      tags: ['Social', 'Analytics', 'Python'] 
    },
    { 
      id: 'deep-scan-analytics', 
      name: 'Deep Scan Analytics', 
      category: 'Hacking & Spam', 
      price: 75, 
      badge: 'PRO', 
      art: 'grid', 
      accent: '#eab786', 
      image: '', 
      subtitle: 'See what others miss.', 
      description: 'Advanced network traffic analysis tool. Visualizes packet flow and identifies anomalies in your local network.', 
      version: '3.0.0', 
      format: 'ZIP / 22 MB', 
      rating: '4.8', 
      reviews: 112, 
      tags: ['Network', 'Analysis', 'GUI'] 
    },
    { 
      id: 'ransom-recovery', 
      name: 'Ransom Recovery Toolkit', 
      category: 'Services', 
      price: 150, 
      badge: 'ESSENTIAL', 
      art: 'cube', 
      accent: '#d59dc5', 
      image: '', 
      subtitle: 'Get your data back.', 
      description: 'A collection of decryption scripts and recovery tools for common ransomware variants. For educational and recovery purposes only.', 
      version: '2023.10', 
      format: 'ZIP / 55 MB', 
      rating: '4.9', 
      reviews: 45, 
      tags: ['Recovery', 'Decryption', 'Security'] 
    },
    { 
      id: 'sql-injection-scanner', 
      name: 'SQLi Scanner Pro', 
      category: 'Hacking & Spam', 
      price: 95, 
      badge: 'TOP RATED', 
      art: 'code', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Find vulnerabilities before they do.', 
      description: 'Automated SQL injection vulnerability scanner for web applications. Generates detailed reports for patching.', 
      version: '4.5.1', 
      format: 'JAR / 12 MB', 
      rating: '4.7', 
      reviews: 230, 
      tags: ['Web', 'Scanner', 'Java'] 
    },
    { 
      id: 'xss-payload-gen', 
      name: 'XSS Payload Generator', 
      category: 'Hacking & Spam', 
      price: 40, 
      badge: '', 
      art: 'terminal', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Test your defenses.', 
      description: 'A comprehensive list of XSS payloads for testing web application security. Includes bypass techniques for WAFs.', 
      version: '1.2.0', 
      format: 'TXT / 1 MB', 
      rating: '4.6', 
      reviews: 180, 
      tags: ['Web', 'Testing', 'Payloads'] 
    },
    { 
      id: 'hash-cracker-edu', 
      name: 'Hash Cracker (Edu)', 
      category: 'Malware Analysis', 
      price: 55, 
      badge: 'LEARNING', 
      art: 'wave', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'Understand password security.', 
      description: 'Educational tool for understanding hash algorithms and password strength. Includes dictionary and brute-force modes for local testing.', 
      version: '2.0.0', 
      format: 'PY / 6 MB', 
      rating: '4.8', 
      reviews: 90, 
      tags: ['Crypto', 'Education', 'Python'] 
    },
    { 
      id: 'stego-tool', 
      name: 'Steganography Suite', 
      category: 'Software', 
      price: 30, 
      badge: '', 
      art: 'orbit', 
      accent: '#eab786', 
      image: '', 
      subtitle: 'Hide in plain sight.', 
      description: 'Embed encrypted messages inside image and audio files. Supports multiple algorithms and password protection.', 
      version: '1.1.0', 
      format: 'ZIP / 10 MB', 
      rating: '4.5', 
      reviews: 75, 
      tags: ['Privacy', 'Encryption', 'Media'] 
    },
    { 
      id: 'dark-web-indexer', 
      name: 'Dark Web Indexer', 
      category: 'Digital Items', 
      price: 120, 
      badge: 'RARE', 
      art: 'grid', 
      accent: '#d59dc5', 
      image: '', 
      subtitle: 'Navigate the unknown.', 
      description: 'A curated database of .onion links and hidden services. Updated weekly. Includes categorization and safety ratings.', 
      version: '2023.11', 
      format: 'DB / 5 MB', 
      rating: '4.9', 
      reviews: 310, 
      tags: ['Database', 'Onion', 'Research'] 
    },
    { 
      id: 'linux-privesc-guide', 
      name: 'Linux PrivEsc Guide', 
      category: 'Guides & Tutorials', 
      price: 20, 
      badge: 'MUST READ', 
      art: 'code', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Master the system.', 
      description: 'A comprehensive guide to Linux privilege escalation techniques. Covers SUID, Sudo, Cron jobs, and kernel exploits.', 
      version: '3.0', 
      format: 'PDF / 15 MB', 
      rating: '5.0', 
      reviews: 450, 
      tags: ['Linux', 'Tutorial', 'Security'] 
    },
    { 
      id: 'metasploit-cheatsheet', 
      name: 'Metasploit Cheat Sheet', 
      category: 'Guides & Tutorials', 
      price: 10, 
      badge: '', 
      art: 'terminal', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Quick reference for pentesters.', 
      description: 'A printable cheat sheet for Metasploit Framework commands. Covers exploitation, post-exploitation, and payloads.', 
      version: '2023', 
      format: 'PDF / 2 MB', 
      rating: '4.7', 
      reviews: 200, 
      tags: ['Metasploit', 'Cheat Sheet', 'Pentest'] 
    },
    { 
      id: 'burner-os-config', 
      name: 'Burner OS Config', 
      category: 'Software', 
      price: 35, 
      badge: 'NEW', 
      art: 'cube', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'Disposable and secure.', 
      description: 'Configuration scripts for setting up a disposable, amnesic operating system environment. Based on Tails OS.', 
      version: '1.0', 
      format: 'SH / 4 MB', 
      rating: '4.6', 
      reviews: 85, 
      tags: ['Tails', 'Privacy', 'Config'] 
    },
    { 
      id: 'anon-dropbox', 
      name: 'Anonymous Dropbox', 
      category: 'Security & Hosting', 
      price: 25, 
      badge: '', 
      art: 'wave', 
      accent: '#eab786', 
      image: '', 
      subtitle: 'Secure file sharing.', 
      description: 'End-to-end encrypted file sharing service with no logs. Files are deleted after download or expiration.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '4.8', 
      reviews: 140, 
      tags: ['Storage', 'Encryption', 'Sharing'] 
    },
    { 
      id: 'blockchain-tracker', 
      name: 'Blockchain Tracker', 
      category: 'Digital Items', 
      price: 80, 
      badge: 'ANALYTICS', 
      art: 'orbit', 
      accent: '#d59dc5', 
      image: '', 
      subtitle: 'Follow the money.', 
      description: 'Tool for tracking cryptocurrency transactions across multiple blockchains. Visualizes wallet connections and flow.', 
      version: '2.2.0', 
      format: 'ZIP / 20 MB', 
      rating: '4.7', 
      reviews: 110, 
      tags: ['Crypto', 'Analytics', 'Tracker'] 
    },
    // --- NEW PRODUCTS ---
    { 
      id: 'bulk-mailer-pro', 
      name: 'Bulk Mailer Pro', 
      category: 'Hacking & Spam', 
      price: 65, 
      badge: 'MARKETING', 
      art: 'terminal', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Reach thousands instantly.', 
      description: 'High-speed email marketing automation tool. Features template builder, list management, and analytics dashboard.', 
      version: '5.0.1', 
      format: 'EXE / 25 MB', 
      rating: '4.5', 
      reviews: 120, 
      tags: ['Email', 'Marketing', 'Automation'] 
    },
    { 
      id: 'smtp-relay-service', 
      name: 'SMTP Relay Service', 
      category: 'Hacking & Spam', 
      price: 30, 
      badge: 'MONTHLY', 
      art: 'grid', 
      accent: '#eab786', 
      image: '', 
      subtitle: 'Reliable delivery.', 
      description: 'Dedicated SMTP relay service for high-volume sending. Includes IP rotation and deliverability optimization.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '4.6', 
      reviews: 85, 
      tags: ['SMTP', 'Email', 'Relay'] 
    },
    { 
      id: 'phish-sim-kit', 
      name: 'Phishing Simulation Kit', 
      category: 'Hacking & Spam', 
      price: 90, 
      badge: 'TRAINING', 
      art: 'orbit', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Test your team.', 
      description: 'Educational phishing simulation platform. Create campaigns to test employee awareness and security posture.', 
      version: '2.1.0', 
      format: 'ZIP / 40 MB', 
      rating: '4.8', 
      reviews: 60, 
      tags: ['Security', 'Training', 'Simulation'] 
    },
    { 
      id: 'sandbox-lite-vm', 
      name: 'Sandbox Lite VM', 
      category: 'Malware Analysis', 
      price: 45, 
      badge: 'ANALYSIS', 
      art: 'cube', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'Safe execution environment.', 
      description: 'Pre-configured virtual machine for safe malware analysis. Includes monitoring tools and snapshot capabilities.', 
      version: '1.0.0', 
      format: 'OVA / 2 GB', 
      rating: '4.9', 
      reviews: 40, 
      tags: ['VM', 'Analysis', 'Security'] 
    },
    { 
      id: 'pe-analyzer-tool', 
      name: 'PE Analyzer Tool', 
      category: 'Malware Analysis', 
      price: 55, 
      badge: 'TECHNICAL', 
      art: 'code', 
      accent: '#d59dc5', 
      image: '', 
      subtitle: 'Inspect executables.', 
      description: 'Detailed analysis tool for Portable Executable files. Extracts headers, imports, exports, and sections.', 
      version: '3.2.0', 
      format: 'EXE / 15 MB', 
      rating: '4.7', 
      reviews: 75, 
      tags: ['PE', 'Analysis', 'Reverse Engineering'] 
    },
    { 
      id: 'yara-rule-scanner', 
      name: 'Yara Rule Scanner', 
      category: 'Malware Analysis', 
      price: 40, 
      badge: 'DETECTION', 
      art: 'wave', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Pattern matching engine.', 
      description: 'Fast and flexible pattern matching tool for malware identification. Includes a library of community Yara rules.', 
      version: '4.1.0', 
      format: 'ZIP / 10 MB', 
      rating: '4.8', 
      reviews: 95, 
      tags: ['Yara', 'Detection', 'Malware'] 
    },
    { 
      id: 'security-consulting', 
      name: 'Security Consulting', 
      category: 'Services', 
      price: 200, 
      badge: 'PREMIUM', 
      art: 'terminal', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Expert advice.', 
      description: 'One-on-one security consulting session. Get personalized advice on hardening your infrastructure and practices.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '5.0', 
      reviews: 25, 
      tags: ['Consulting', 'Security', 'Expert'] 
    },
    { 
      id: 'data-recovery-pro', 
      name: 'Data Recovery Pro', 
      category: 'Services', 
      price: 120, 
      badge: 'RECOVERY', 
      art: 'grid', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'Lost data? We help.', 
      description: 'Professional data recovery service for corrupted drives and deleted files. High success rate for common scenarios.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '4.6', 
      reviews: 50, 
      tags: ['Recovery', 'Data', 'Service'] 
    },
    { 
      id: 'server-admin-service', 
      name: 'Server Admin Service', 
      category: 'Services', 
      price: 80, 
      badge: 'MANAGEMENT', 
      art: 'orbit', 
      accent: '#eab786', 
      image: '', 
      subtitle: 'We manage, you relax.', 
      description: 'Managed server administration service. Includes updates, monitoring, backups, and security patching.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '4.7', 
      reviews: 35, 
      tags: ['Admin', 'Server', 'Management'] 
    },
    { 
      id: 'offshore-vps-hosting', 
      name: 'Offshore VPS Hosting', 
      category: 'Security & Hosting', 
      price: 20, 
      badge: 'PRIVACY', 
      art: 'cube', 
      accent: '#d59dc5', 
      image: '', 
      subtitle: 'Host without limits.', 
      description: 'VPS hosting in offshore locations with strong privacy laws. No logs, anonymous payment accepted.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '4.5', 
      reviews: 150, 
      tags: ['VPS', 'Hosting', 'Offshore'] 
    },
    { 
      id: 'bulletproof-dns', 
      name: 'Bulletproof DNS', 
      category: 'Security & Hosting', 
      price: 35, 
      badge: 'RESILIENT', 
      art: 'wave', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Always online.', 
      description: 'Highly resilient DNS hosting service. Resistant to takedowns and DDoS attacks. Ensures your domains stay up.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '4.8', 
      reviews: 70, 
      tags: ['DNS', 'Hosting', 'Resilient'] 
    },
    { 
      id: 'encrypted-email-host', 
      name: 'Encrypted Email Host', 
      category: 'Security & Hosting', 
      price: 15, 
      badge: 'SECURE', 
      art: 'code', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Private communication.', 
      description: 'End-to-end encrypted email hosting. Zero-knowledge architecture ensures only you can read your messages.', 
      version: 'N/A', 
      format: 'Service', 
      rating: '4.9', 
      reviews: 200, 
      tags: ['Email', 'Encryption', 'Privacy'] 
    },
    { 
      id: 'social-eng-guide', 
      name: 'Social Engineering Guide', 
      category: 'Guides & Tutorials', 
      price: 25, 
      badge: 'PSYCHOLOGY', 
      art: 'terminal', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'The human element.', 
      description: 'Comprehensive guide to social engineering techniques. Covers pretexting, phishing, and influence tactics.', 
      version: '2.0', 
      format: 'PDF / 20 MB', 
      rating: '4.7', 
      reviews: 110, 
      tags: ['Social Engineering', 'Guide', 'Psychology'] 
    },
    { 
      id: 'lockpicking-guide', 
      name: 'Lockpicking Guide', 
      category: 'Guides & Tutorials', 
      price: 15, 
      badge: 'SKILL', 
      art: 'grid', 
      accent: '#eab786', 
      image: '', 
      subtitle: 'Open any lock.', 
      description: 'Step-by-step guide to lockpicking. Includes diagrams, tool recommendations, and practice exercises.', 
      version: '1.5', 
      format: 'PDF / 10 MB', 
      rating: '4.8', 
      reviews: 90, 
      tags: ['Lockpicking', 'Guide', 'Skill'] 
    },
    { 
      id: 'surveillance-detection', 
      name: 'Surveillance Detection', 
      category: 'Guides & Tutorials', 
      price: 30, 
      badge: 'COUNTER-INTEL', 
      art: 'orbit', 
      accent: '#d59dc5', 
      image: '', 
      subtitle: 'Stay unseen.', 
      description: 'Guide to detecting and evading surveillance. Covers physical and digital surveillance countermeasures.', 
      version: '1.2', 
      format: 'PDF / 15 MB', 
      rating: '4.9', 
      reviews: 65, 
      tags: ['Surveillance', 'Counter-Intel', 'Guide'] 
    },
    { 
      id: 'encrypted-os-config', 
      name: 'Encrypted OS Config', 
      category: 'Software', 
      price: 40, 
      badge: 'SECURITY', 
      art: 'cube', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Full disk encryption.', 
      description: 'Configuration scripts for setting up full disk encryption on Linux. Supports LUKS and VeraCrypt.', 
      version: '1.1', 
      format: 'SH / 5 MB', 
      rating: '4.7', 
      reviews: 55, 
      tags: ['Encryption', 'OS', 'Config'] 
    },
    { 
      id: 'password-gen-pro', 
      name: 'Password Gen Pro', 
      category: 'Software', 
      price: 20, 
      badge: 'UTILITY', 
      art: 'wave', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Unbreakable passwords.', 
      description: 'Advanced password generator with customizable rules. Supports passphrases, symbols, and entropy checking.', 
      version: '2.0', 
      format: 'EXE / 8 MB', 
      rating: '4.6', 
      reviews: 130, 
      tags: ['Password', 'Generator', 'Utility'] 
    },
    { 
      id: 'file-shredder-secure', 
      name: 'File Shredder Secure', 
      category: 'Software', 
      price: 25, 
      badge: 'ERASE', 
      art: 'code', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'Gone forever.', 
      description: 'Secure file deletion tool. Overwrites data multiple times to prevent recovery. Supports batch processing.', 
      version: '1.3', 
      format: 'EXE / 6 MB', 
      rating: '4.8', 
      reviews: 80, 
      tags: ['Shredder', 'Privacy', 'Utility'] 
    },
    { 
      id: 'prop-id-templates', 
      name: 'Prop ID Templates', 
      category: 'Digital Items', 
      price: 30, 
      badge: 'PROP', 
      art: 'terminal', 
      accent: '#eab786', 
      image: '', 
      subtitle: 'For movies and art.', 
      description: 'High-quality templates for prop IDs. Perfect for film production, theater, and art projects.', 
      version: '1.0', 
      format: 'PSD + AI / 50 MB', 
      rating: '4.5', 
      reviews: 45, 
      tags: ['Prop', 'Template', 'Design'] 
    },
    { 
      id: 'prop-passport-templates', 
      name: 'Prop Passport Templates', 
      category: 'Digital Items', 
      price: 35, 
      badge: 'PROP', 
      art: 'grid', 
      accent: '#d59dc5', 
      image: '', 
      subtitle: 'Cinematic realism.', 
      description: 'Realistic passport templates for props. Includes editable fields and high-resolution graphics.', 
      version: '1.0', 
      format: 'PSD + AI / 60 MB', 
      rating: '4.6', 
      reviews: 30, 
      tags: ['Prop', 'Passport', 'Design'] 
    },
    { 
      id: 'can-bus-sniffer', 
      name: 'CAN Bus Sniffer', 
      category: 'Automotive Related', 
      price: 70, 
      badge: 'HARDWARE', 
      art: 'orbit', 
      accent: '#b9f563', 
      image: '', 
      subtitle: 'Listen to your car.', 
      description: 'Software for interfacing with CAN bus networks. Captures and analyzes vehicle communication data.', 
      version: '2.1', 
      format: 'ZIP / 12 MB', 
      rating: '4.7', 
      reviews: 50, 
      tags: ['CAN Bus', 'Automotive', 'Analysis'] 
    },
    { 
      id: 'immobilizer-sim', 
      name: 'Immobilizer Simulator', 
      category: 'Automotive Related', 
      price: 50, 
      badge: 'EDUCATIONAL', 
      art: 'cube', 
      accent: '#b6a1ed', 
      image: '', 
      subtitle: 'Understand security.', 
      description: 'Educational simulator for car immobilizer systems. Learn how they work and how to test them safely.', 
      version: '1.0', 
      format: 'EXE / 20 MB', 
      rating: '4.5', 
      reviews: 35, 
      tags: ['Immobilizer', 'Simulator', 'Education'] 
    },
    { 
      id: 'key-programmer-sw', 
      name: 'Key Programmer SW', 
      category: 'Automotive Related', 
      price: 90, 
      badge: 'PRO', 
      art: 'wave', 
      accent: '#7dc9d6', 
      image: '', 
      subtitle: 'Program keys.', 
      description: 'Software for programming automotive keys. Supports a wide range of vehicle makes and models.', 
      version: '3.0', 
      format: 'EXE / 30 MB', 
      rating: '4.8', 
      reviews: 60, 
      tags: ['Key', 'Programmer', 'Automotive'] 
    },
    // --- NEW DARK WEB CATEGORY PRODUCTS ---
    { 
      id: 'cvv-dump-fresh', 
      name: 'Fresh CVV Dumps [US/UK]', 
      category: 'Fraud', 
      price: 15, 
      badge: 'FRESH', 
      art: 'terminal', 
      accent: '#ff0000', 
      image: '', 
      subtitle: 'High approval rate.', 
      description: 'Verified CVV dumps from major banks. High approval rate for online purchases. Includes BIN info and zip code.', 
      version: 'Daily', 
      format: 'TXT / List', 
      rating: '4.8', 
      reviews: 500, 
      tags: ['CVV', 'Dumps', 'Carding'] 
    },
    { 
      id: 'fullz-info', 
      name: 'Fullz Info Package [US]', 
      category: 'Fraud', 
      price: 40, 
      badge: 'PREMIUM', 
      art: 'grid', 
      accent: '#ff0000', 
      image: '', 
      subtitle: 'Complete identity.', 
      description: 'Complete identity package including SSN, DOB, Address, and Mother\'s Maiden Name. Verified data.', 
      version: 'Weekly', 
      format: 'PDF / TXT', 
      rating: '4.9', 
      reviews: 320, 
      tags: ['Fullz', 'Identity', 'Data'] 
    },
    { 
      id: 'bank-logs-access', 
      name: 'Bank Log Access [Chase/BoA]', 
      category: 'Fraud', 
      price: 80, 
      badge: 'RARE', 
      art: 'orbit', 
      accent: '#ff0000', 
      image: '', 
      subtitle: 'Direct access.', 
      description: 'Direct access to online banking accounts. Verified balance over $1000. Includes 2FA bypass instructions.', 
      version: 'Daily', 
      format: 'TXT', 
      rating: '4.7', 
      reviews: 150, 
      tags: ['Bank Logs', 'Access', 'Money'] 
    },
    { 
      id: 'mdma-crystals', 
      name: 'MDMA Crystals [High Purity]', 
      category: 'Drugs & Chemicals', 
      price: 60, 
      badge: 'BESTSELLER', 
      art: 'wave', 
      accent: '#00ff00', 
      image: '', 
      subtitle: '99% Purity.', 
      description: 'High quality MDMA crystals. Tested for purity. Vacuum sealed packaging. Discreet shipping.', 
      version: 'In Stock', 
      format: 'Grams', 
      rating: '4.9', 
      reviews: 1200, 
      tags: ['MDMA', 'Stimulant', 'Party'] 
    },
    { 
      id: 'cannabis-og-kush', 
      name: 'OG Kush Cannabis [Indoor]', 
      category: 'Drugs & Chemicals', 
      price: 45, 
      badge: 'ORGANIC', 
      art: 'cube', 
      accent: '#00ff00', 
      image: '', 
      subtitle: 'Top shelf.', 
      description: 'Premium indoor grown OG Kush. High THC content. Dense buds with strong aroma. 3.5g packs.', 
      version: 'Fresh', 
      format: 'Grams', 
      rating: '4.8', 
      reviews: 800, 
      tags: ['Cannabis', 'Weed', 'Indoor'] 
    },
    { 
      id: 'lsd-blotters', 
      name: 'LSD Blotters [200ug]', 
      category: 'Drugs & Chemicals', 
      price: 25, 
      badge: 'PSYCHEDELIC', 
      art: 'code', 
      accent: '#00ff00', 
      image: '', 
      subtitle: 'Strong trip.', 
      description: 'High potency LSD blotters. 200ug per tab. Vivid visuals and long duration. 10 tabs per sheet.', 
      version: 'Batch 4', 
      format: 'Tabs', 
      rating: '4.9', 
      reviews: 600, 
      tags: ['LSD', 'Acid', 'Psychedelic'] 
    },
    { 
      id: 'fake-passport-eu', 
      name: 'Fake Passport [EU Schengen]', 
      category: 'Counterfeit Items', 
      price: 1500, 
      badge: 'TOP TIER', 
      art: 'terminal', 
      accent: '#ffff00', 
      image: '', 
      subtitle: 'Scannable.', 
      description: 'High quality counterfeit passport. Scannable MRZ and RFID chip. Realistic holograms. 2 week production time.', 
      version: '2023', 
      format: 'Physical', 
      rating: '4.9', 
      reviews: 200, 
      tags: ['Passport', 'Travel', 'Document'] 
    },
    { 
      id: 'driver-license-us', 
      name: 'Driver License [US All States]', 
      category: 'Counterfeit Items', 
      price: 250, 
      badge: 'FAST', 
      art: 'grid', 
      accent: '#ffff00', 
      image: '', 
      subtitle: 'Real ID compliant.', 
      description: 'Counterfeit driver\'s license for any US state. Real ID compliant. Holograms and UV features included.', 
      version: '2024', 
      format: 'Physical', 
      rating: '4.7', 
      reviews: 450, 
      tags: ['License', 'ID', 'US'] 
    },
    { 
      id: 'counterfeit-currency-usd', 
      name: 'Counterfeit Currency [USD $100]', 
      category: 'Counterfeit Items', 
      price: 24, 
      badge: 'TOP TIER', 
      art: 'orbit', 
      accent: '#ffff00', 
      image: '', 
      subtitle: '1:1 quality.', 
      description: 'High quality replica $100 bills. Printed with a special blend of paper using 75% cotton and 25% Linen. Sequential serials.', 
      version: 'Series 2013', 
      format: 'Stack', 
      rating: '4.5', 
      reviews: 100, 
      tags: ['Money','Replica'] 
    }
  ]
};
/* Separate fictional inventory for the non-executing Autoshop prop screen.
   Edit names/prices here. These entries never connect to checkout or a seller. */
window.MARKET.autoshopProps = [
  {id:'prop-code', name:'Source Archive Bundle', price:45},
  {id:'prop-ui', name:'Interface Toolkit', price:30},
  {id:'prop-theme', name:'Midnight Theme Collection', price:12},
  {id:'prop-lab', name:'Offline Learning Lab', price:25}
];
