// Generated by scripts/build-update.cjs. Edit scripts/sw-template.js instead.
const PREFIX = `tornet-app:${self.registration.scope}:`;
const CACHE = PREFIX + 'f9ade10e5b2812b53fd8';
const FILES = ["ProductImages/.gitkeep","ProductImages/BankLog.png","ProductImages/CANBus.png","ProductImages/CVVDump.png","ProductImages/DataRecoveryPro.png","ProductImages/FullzInfo.png","ProductImages/HackerForHire.png","ProductImages/HitmanForHire.png","ProductImages/Immobilizer.png","ProductImages/KeyProgrammer.png","ProductImages/LSD.png","ProductImages/License.png","ProductImages/MDMA.png","ProductImages/Money.png","ProductImages/OGkush.png","ProductImages/Passport.png","ProductImages/RansomRecoveryToolkit.png","ProductImages/SecurityConsulting.png","ProductImages/ServerAdminService.png","ProductImages/tornet-product-vault.png","assets/apple-touch-icon.png","assets/background.jpg","assets/favicon.png","assets/icon-192.png","assets/icon-512.png","assets/icon-original.png","assets/logo-original.png","assets/logo.png","assets/oni-apple-touch-180.png","assets/oni-favicon-32.png","assets/oni-favicon-48.png","assets/oni-icon-192.png","assets/oni-icon-512.png","assets/oni-maskable-512.png","assets/oni-motion.gif","assets/oni-still.png","autoshop.js","feedback.js","index.html","manifest.webmanifest","products.js","rates.js","script.js","styles.css","updates.js"];
const absolute = path => new URL(path,self.registration.scope).href;
const SHELL = new Set(FILES.map(absolute));
self.addEventListener('install',event=>{
 event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(FILES.map(file=>new Request(absolute(file),{cache:'reload'})))));
});
self.addEventListener('activate',event=>{
 event.waitUntil((async()=>{
  for(const key of await caches.keys())if(key.startsWith(PREFIX)&&key!==CACHE)await caches.delete(key);
  await self.clients.claim();
 })());
});
self.addEventListener('message',event=>{
 if(event.data?.type==='SKIP_WAITING')event.waitUntil(self.skipWaiting());
});
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url);
 if(!url.href.startsWith(self.registration.scope))return;
 // Update checks must reach the server; never serve a cached worker script.
 if(url.pathname===new URL('sw.js',self.registration.scope).pathname)return;
 let target=url.origin+url.pathname;
 if(target===self.registration.scope)target=absolute('index.html');
 if(!SHELL.has(target))return;
 event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(target))||fetch(event.request)));
});
